[[vk::binding(0, 0)]]
cbuffer Constants {
    float4x4 mvp;
    uint2 viewport_size;
    uint2 pad;
};

[[vk::binding(0, 1)]]
RWTexture2D<float4> output_image;

[[vk::binding(1, 1)]]
RWTexture2D<float4> swapchain_image;

[numthreads(32, 32, 1)]
void main(uint3 dispatch_thread_id : SV_DispatchThreadID) {
    int2 loc = int2(dispatch_thread_id.xy);
    if (loc.x < viewport_size.x && loc.y < viewport_size.y) {
        swapchain_image[loc] = output_image.Load(loc);
    }
}
